### ISSUE TITLE
Merge PR #15 Failed

### ISSUE THREAD

**Issue by tmeliberty** [Burgov/KeyValueFormBundle#16]
Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW) in /Form/Type/KeyValueType.php on line 74:
$resolver->setAllowedTypes('allowed_keys' => array('null', 'array'));

should be :
$resolver->setAllowedTypes(array('allowed_keys' => array('null', 'array')));

**Comment by yellow1912** [comment]
This is causing serious error for us as well

**Comment by yellow1912** [comment]
PR https://github.com/Burgov/KeyValueFormBundle/pull/17 here

**Comment by Burgov** [comment]
fixed in 1.3.1
